globophoto/photo/urls.py
from django.conf.urls import patterns, url

from globophoto.photo.views import (
    GalleryView, PhotoListView, PhotoCreateView,
    PhotoUpdateView, PhotoDeleteView
)

urlpatterns = patterns(
    '',
    url(r'^$', GalleryView.as_view(), name='home'),
    url(r'^photos/$', PhotoListView.as_view(), name='list'),
    url(r'^photos/new/$', PhotoCreateView.as_view(), name='create'),
    url(r'^photos/update/(?P<pk>[\d]+)/$', PhotoUpdateView.as_view(),
        name='update'),
    url(r'^photos/delete/(?P<pk>[\d]+)/$', PhotoDeleteView.as_view(),
        name='delete'),
)

globophoto/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'', include('globophoto.photo.urls', namespace='photo')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

globophoto/photo/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _


class Photo(models.Model):
    """
    Model that represent photos in project.

    :param name: The name of photo
    :type name: str.
    :param image: The photo uploaded
    :type image: file.
    :param created_at: When image was created
    :type created_at: datetime
    """
    name = models.CharField(_(u"Nome da Imagem"), max_length=255)
    image = models.ImageField(_(u"Imagem"), upload_to="images", max_length=255)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=True)

    class Meta:
        db_table = 'photos'
        verbose_name = _(u"foto")
        verbose_name_plural = _(u"fotos")
        ordering = ['-created_at']

    def __unicode__(self):
        return self.name

    @property
    def filename(self):
        """Parse file path to return filename"""
        return self.image.name.split('/')[-1]


from globophoto.photo import signals

globophoto/photo/forms.py
# -*- coding: utf-8 -*-

from django import forms

from globophoto.photo.models import Photo


class PhotoForm(forms.ModelForm):
    """Form used to insert photos"""
    class Meta:
        model = Photo
        exclude = ['name']

globophoto/photo/views.py
# -*- coding: utf-8 -*-

from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

from globophoto.photo.models import Photo
from globophoto.photo.forms import PhotoForm


class GalleryView(ListView):
    template_name = "photo/gallery.html"
    model = Photo


class PhotoListView(ListView):
    model = Photo


class PhotoCreateView(CreateView):
    model = Photo
    form_class = PhotoForm
    success_url = reverse_lazy('photo:list')


class PhotoUpdateView(UpdateView):
    template_name = "photo/photo_form.html"
    model = Photo
    form_class = PhotoForm
    success_url = reverse_lazy('photo:list')


class PhotoDeleteView(DeleteView):
    model = Photo
    success_url = reverse_lazy('photo:list')

globophoto/photo/templates/photo/gallery.html
{% extends "base.html" %}
{% load staticfiles %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/gallery.css' %}">
{% endblock styles %}

{% block main %}
    <div class="col-md-12">
        {% if object_list %}
            <div id="gallery">
                <a href="#" id="left-arrow"><img src="{% static 'img/seta_esquerda.jpg' %}" alt=""></a>
                <a href="#" id="right-arrow"><img src="{% static 'img/seta_direita.jpg' %}" alt=""></a>
                <div id="photos">
                    {% for photo in object_list %}
                        <img src="{{ photo.image.url }}" alt="{{ photo.image.name }}" width="800" height="400">
                    {% endfor %}
                </div>
            </div>
            <br>
            <div class="col-md-12 text-center well">
                <h4>Caso está sem paciência com o seu mouse, use as setas 
                <img src="{% static 'img/key_left.png' %}" alt="" width="24" height="24"> e <img src="{% static 'img/key_right.png' %}" alt="" width="24" height="24"></h4>
            </div>
        {% else %}
            <div class="page-header">
                <h1>Estamos sem foto agora</h1>
                <p>Percebi que está vendo essa página sem foto. Isso é porque não cadastrou nenhuma. O que acha de <a href="{% url 'photo:list' %}">fazer isso agora?</a></p>
            </div>
        {% endif %}
    </div>
{% endblock main %}

{% block scripts %}
    {{ block.super }}
    <script src="{% static 'js/gallery.js' %}"></script>
{% endblock scripts %}

globophoto/photo/templates/photo/photo_confirm_delete.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
    <form class="form well" action="" method="POST">
        {% csrf_token %}
        <h2>{% trans "Realmente deseja remover a photo" %} "{{ object }}"?</h2>
        <img src="{{ object.image.url }}" alt="{{ object.image.name }}" class="img-thumbnail" width="512" height="512">
        <br><br>
        <input class="btn btn-lg btn-success" type="submit" value="Sim" /> {% trans "ou" %}
        <a class="btn btn-lg btn-default" href="{% url 'photo:list' %}">Não</a>
    </form>
{% endblock main %}

globophoto/photo/templates/photo/photo_form.html
{% extends "base.html" %}
{% load i18n %}

{% block main %}
    <div class="col-md-12">
        {% if object.pk %}
            <h1>{% trans "Editar Foto" %}</h1>
        {% else %}
            <h1>{% trans "Nova Foto" %}</h1>
        {% endif %}
        <hr>
        <form class="form well" enctype="multipart/form-data" action="" method="POST">
            {% csrf_token %}
            {% if object.pk %}
                <img src="{{ photo.image.url }}" alt="{{ photo.name }}" class="img-thumbnail" width="256" height="256">
            {% endif %}
            {{ form.as_p }}
            <br>
            <input class="btn btn-lg btn-success" type="submit" value="Salvar"> {% trans "ou" %} 
            <a class="btn btn-lg btn-default" href="{% url 'photo:list' %}">Voltar</a>
        </form>
    </div>
{% endblock main %}

globophoto/photo/templates/photo/photo_list.html
{% extends "base.html" %}
{% load i18n %}

{% block styles %}
    {{ block.super }}
    <style>
        .middle-cell {
            vertical-align: middle !important;
        }
    </style>
{% endblock styles %}

{% block main %}
    <div class="col-md-12">
        {% if object_list %}
            <h1>{% trans "Listar Fotos" %}</h1>
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>{% trans "Opções" %}</th>
                        <th>{% trans "Imagem" %}</th>
                        <th>{% trans "Nome da Imagem" %}</th>
                        <th>{% trans "Link da Imagem" %}</th>
                    </tr>
                </thead>
                <tbody>
                    {% for photo in object_list %}
                        <tr>
                            <td>
                                <a href="{% url 'photo:update' photo.pk %}"><i class="fa fa-pencil"></i> {% trans "Editar" %}</a>
                                <a href="{% url 'photo:delete' photo.pk %}"><i class="fa fa-trash-o"></i> {% trans "Excluir" %}</a>
                            </td>
                            <td><img src="{{ photo.image.url }}" alt="{{ photo.name }}" class="img-thumbnail" width="100" height="100"></td>
                            <td class="middle-cell">{{ photo.name }}</td>
                            <td class="middle-cell"><a target="_blank" href="{{ photo.image.url }}">{% trans "Download da Foto" %}</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="page-header">
                <h1>Nenhuma foto inserida. Fique à vontade pra cadastrar!</h1>
            </div>
        {% endif %}
    </div>
    <div class="col-md-12">
        <a class="btn btn-lg btn-success" href="{% url 'photo:create' %}">Adicionar Foto</a> {% trans "ou" %}
        <a class="btn btn-lg btn-default" href="{% url 'photo:home' %}">Voltar</a>
    </div>
{% endblock main %}

globophoto/templates/base.html
{% load i18n staticfiles active_page %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    {% block meta %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">
    {% endblock meta %}

    {% block title %}
        <title>Globo Photo</title>
    {% endblock title %}

    {% block styles %}
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}">
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
        <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    {% endblock styles %}

    {% block extra_head %}
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    {% endblock extra_head %}
  </head>

  <body>

    {% block navbar %}
        <div class="navbar navbar-default navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'photo:home' %}">
                <img src="{% static 'img/logo.png' %}" alt="" width="24" height="24">
                Globo Photo
            </a>
            </div>
            <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="{% active_page request 'photo:home' %}"><a href="{% url 'photo:home' %}">{% trans "Galeria" %}</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="{% active_page request 'photo:list' %}"><a href="{% url 'photo:list' %}">{% trans "Gerenciar as Fotos" %}</a></li>
            </ul>
            </div><!--/.nav-collapse -->
        </div>
        </div>
    {% endblock navbar %}


    <div class="container">
        {% block main %} {% endblock main %}
    </div> <!-- /container -->


    {% block scripts %}
        <!-- Bootstrap core JavaScript
        ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
    {% endblock scripts %}
  </body>
</html>